---
name: maktaba
description: Islamic Library .
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cached_network_image: null
  flutter_plugin_pdf_viewer: any
  share: ^0.6.3+1
  launch_review: ^2.0.0
  path_provider: null
  dio: any
  flash: any
  permission_handler: ^5.0.1+1
  flutter_full_pdf_viewer: ^1.0.6
  percent_indicator: ^2.1.1
  simple_url_preview: null
  font_awesome_flutter: ^8.8.1
  provider: ^4.3.2+2
  lottie: ^0.6.0
  get: ^3.13.2
  shared_preferences: ^0.5.12+2
  flutter_screenutil: ^3.1.1
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.0
  flutter_pdfview: ^1.0.0+6
  intl: ^0.16.1
  universal_html: ^1.2.3
  pdf_text: ^0.3.1
  in_app_review:
  syncfusion_flutter_pdfviewer: ^18.3.44-beta
  advance_pdf_viewer: any
  epub_viewer: ^0.1.9
  flutter_modular:
  after_layout:
  flutter_fullpdfview:
  statusbar_util:
  i18n:
  flutter_localizations:
    sdk: flutter
  easy_localization: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
flutter_intl:
  enabled: true
